[theme]
base = "dark"
primaryColor = "#9085e9"
backgroundColor = "#121017"
secondaryBackgroundColor = "#1a1722"
textColor = "#f3f1f8"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
